# Generated by Django 4.0.5 on 2022-07-12 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_category_game_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['pk'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['pk'], 'verbose_name': 'list', 'verbose_name_plural': 'lists'},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.list'),
        ),
    ]
