# Generated by Django 4.0.5 on 2022-07-12 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_category_options_alter_list_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['pk']},
        ),
    ]
