# Generated by Codex on 2026-04-11

from django.db import migrations, models


def clamp_record_ratings(apps, _schema_editor):
    """Keep existing data compatible with the new rating constraint."""
    record = apps.get_model("games", "Record")
    record.objects.filter(rating__gt=5).update(rating=5)


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0006_alter_user_options"),
    ]

    operations = [
        migrations.RunPython(clamp_record_ratings, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="record",
            constraint=models.CheckConstraint(
                condition=models.Q(rating__gte=0, rating__lte=5),
                name="record_rating_between_0_and_5",
            ),
        ),
    ]
