---
name: Destruction
on: workflow_dispatch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  destruction:
    name: Destruction
    runs-on: ubuntu-latest
    env:
      PROJECT: games
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Install kubectl
        uses: azure/setup-kubectl@v4.0.0

      - name: Configure kubectl
        run: |
          mkdir ~/.kube
          echo "$KUBECONFIG" > ~/.kube/config
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }} # Done as a variable because it doesn't work in place.

      - name: Destroy
        run: |
          kubectl delete -f deployment --ignore-not-found
          kubectl delete secret "$PROJECT" --ignore-not-found
