---
name: Remove Unused Games
on:
  schedule:
    - cron: "0 7 1 * *" # Runs at 07:00 UTC (03:00 EDT) on the first day of the month
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  remove_unused_games:
    name: Remove unused games
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.0

      - name: Install kubectl
        uses: azure/setup-kubectl@v3.2

      - name: Configure kubectl
        run: |
          mkdir ~/.kube
          echo "$KUBECONFIG" > ~/.kube/config
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }} # Done as a variable because it doesn't work in place.

      - name: Remove unused games
        run: make prod-manage remove_unused_games
