---
name: Reusable Test
on:
  workflow_call:
jobs:
  reusable_test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: "3.11"
          # This is not working currently. See https://github.com/actions/setup-python/issues/369
          # cache: poetry
          # cache-dependency-path: poetry.lock

      - name: Use pip cache
        uses: actions/cache@v3.3.2
        with:
          path: ~/.cache/pip
          key: pip

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org
          # This is not working currently
          # cache: yarn
          # cache-dependency-path: frontend/yarn.lock

      - name: Use tox cache
        uses: actions/cache@v3.3.2
        with:
          path: .tox
          key: tox-${{ hashFiles('poetry.lock') }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: |
          cd frontend
          echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Use yarn cache
        uses: actions/cache@v3.3.2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ hashFiles('frontend/yarn.lock') }}
          restore-keys: |
            yarn-

      - name: Install linters binaries
        run: make install-linters-binaries

      - name: Install shellcheck
        run: sudo apt install shellcheck -y

      - name: Install main Python dependencies
        run: make install-main-python-deps

      - name: Install Python requirements
        run: tox -e py-requirements

      - name: Install yarn
        run: sudo npm install yarn@2.4.3 --location=global

      - name: Install js dependencies
        run: |
          make yarn-install-locked

      - name: Run tests
        run: make test

      - name: Run codecov
        uses: codecov/codecov-action@v3.1.4
