---
name: Reusable Restart App
on:
  workflow_call:
jobs:
  reusable_restart_app:
    name: Restart app
    runs-on: ubuntu-latest
    env:
      PROJECT: games
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Install kubectl
        uses: azure/setup-kubectl@v4.0.1

      - name: Configure kubectl
        run: |
          mkdir ~/.kube
          echo "$KUBECONFIG" > ~/.kube/config
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }} # Done as a variable because it doesn't work in place.

      - name: Install doctl
        uses: digitalocean/action-doctl@v2.5.1
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Restart app
        run: |
          kubectl apply -f deployment
          kubectl create secret generic "$PROJECT" --from-literal=DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
            --from-literal=SECRET_KEY="${{ secrets.SECRET_KEY }}" \
            --from-literal=IGDB_CLIENT_ID="${{ secrets.IGDB_CLIENT_ID }}" \
            --from-literal=IGDB_CLIENT_SECRET=${{ secrets.IGDB_CLIENT_SECRET }} \
            --from-literal=SENTRY_DSN=${{ secrets.SENTRY_DSN }} \
            --from-literal=EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }} \
            --dry-run=client -o yaml | kubectl apply -f -
          kubectl rollout restart "deployment/$PROJECT"
          kubectl rollout status "deployment/$PROJECT"
