---
name: Reusable Test
on:
  workflow_call:
jobs:
  reusable_test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: "./requirements*.txt"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org
          # This is not working currently
          # cache: yarn
          # cache-dependency-path: frontend/yarn.lock

      - name: Use tox cache
        uses: actions/cache@v3
        with:
          path: .tox
          key: tox-${{ hashFiles('requirements.txt', 'requirements-dev.txt') }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: |
          cd frontend
          echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ hashFiles('frontend/yarn.lock') }}
          restore-keys: |
            yarn-

      - name: Install linters binaries
        run: make install-linters-binaries

      - name: Install shellcheck
        run: sudo apt install shellcheck -y

      - name: Install tox
        run: pip install tox

      - name: Install python requirements
        run: tox -e py-requirements

      - name: Install yarn
        run: sudo npm install yarn@2.4.3 --location=global

      - name: Install js dependencies
        run: |
          make yarn-install-locked

      - name: Run tests
        run: make test

      - name: Run codecov
        uses: codecov/codecov-action@v3
